version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5430:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: okon
      POSTGRES_USER: okon
      POSTGRES_DB: scorehubdb